# Assignment 3
## Implementation of Trust Rank Algorithm
### Submitted By:
### Naitik Malav-CS19BTECH11026, Jai Goyal-CS19BTECH11027

In [321]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
import operator
from networkx.drawing.nx_agraph import to_agraph 

In [299]:
df = pd.read_csv('graph.txt', delimiter=' ', header=None)

In [300]:
df

0     1
0         0     1
1         0     2
2         0     3
3         0     4
4         0     5
...     ...   ...
88229  4026  4030
88230  4027  4031
88231  4027  4032
88232  4027  4038
88233  4031  4038

[88234 rows x 2 columns]

In [301]:
def getNodes(df):
    nodes = []
    for i in range(len(df)):
        u = df.iloc[i, 0]
        v = df.iloc[i, 1]

        if u not in nodes:
            nodes.append(u)
        if v not in nodes:
            nodes.append(v)
    
    return nodes

In [302]:
def nodes_dictionary(df):    
    nodes_dict = {}
    for i in range(len(df)):
        u = df.iloc[i, 0]
        v = df.iloc[i, 1]

        if u not in nodes_dict:
            nodes_dict[u] = [v]
        else:
            nodes_dict[v] = [u]
            
    return nodes_dict

In [303]:
def getMatrixSize(df):
    size = 0
    for i in range(len(df)):
        u = df.iloc[i, 0]
        v = df.iloc[i, 1]
        
        if size < u:
            size = u
        if size < v:
            size = v
    
    return size

In [304]:
nodes_dict = nodes_dictionary(df)
nodes = getNodes(df)
size = getMatrixSize(df)

In [305]:
print(len(nodes))
print(len(nodes_dict))
print(size)

4039
4039
4038


In [306]:
def transitionMatrix(size, Dict):
    T = np.zeros((size+1, size+1))
    print(T.shape)
    for u in nodes_dict:
        for v in nodes_dict[u]:
            T[u][v] = 1/len(nodes_dict[u])
            
    return T

In [307]:
T = transitionMatrix(size, nodes_dict)

(4039, 4039)


In [309]:
D = np.zeros(size+1)
for i in range(1, size + 1):
    if i in nodes:
        D[i] = 1/len(nodes)     

In [310]:
len(D)

4039

In [311]:
def getIterationCount(T, d, beta):
    const = (1-beta)*d
    count = 0
    T = beta*T

    while(1):
        v1 = np.dot(T, d) + const
        if np.array_equal(v1, d):
            break
            
        else:
            d = v1
            count += 1
            
    return count

In [312]:
count = getIterationCount(T, D, 0.85)
print("No. of iterations required without considering Trust Rank: " + str(count))

No. of iterations required without considering Trust Rank: 240


In [313]:
TrustRankScore = []
for i in range(1, len(v)):
    if D[i] != 0:
        TrustRankScore.append([i, v[i]])
        
TrustRankScore = sorted(TrustRankScore, key = operator.itemgetter(1), reverse = True)
trusted_pages = []
for i, page in zip(range(0, int(0.4*len(TrustRankScore))), TrustRankScore):
    trusted_pages.append(page[0])
    
D = np.zeros(size + 1)
for i in range(1, size + 1):
    if i in trusted_pages:
        D[i] = int(0.4*len(TrustRankScore))

In [314]:
print(TrustRankScore)

[[1, 1615.0], [2, 1615.0], [3, 1615.0], [4, 1615.0], [5, 1615.0], [6, 1615.0], [7, 1615.0], [8, 1615.0], [9, 1615.0], [10, 1615.0], [11, 1615.0], [12, 1615.0], [13, 1615.0], [14, 1615.0], [15, 1615.0], [16, 1615.0], [17, 1615.0], [18, 1615.0], [19, 1615.0], [20, 1615.0], [21, 1615.0], [22, 1615.0], [23, 1615.0], [24, 1615.0], [25, 1615.0], [26, 1615.0], [27, 1615.0], [28, 1615.0], [29, 1615.0], [30, 1615.0], [31, 1615.0], [32, 1615.0], [33, 1615.0], [34, 1615.0], [35, 1615.0], [36, 1615.0], [37, 1615.0], [38, 1615.0], [39, 1615.0], [40, 1615.0], [41, 1615.0], [42, 1615.0], [43, 1615.0], [44, 1615.0], [45, 1615.0], [46, 1615.0], [47, 1615.0], [48, 1615.0], [49, 1615.0], [50, 1615.0], [51, 1615.0], [52, 1615.0], [53, 1615.0], [54, 1615.0], [55, 1615.0], [56, 1615.0], [57, 1615.0], [58, 1615.0], [59, 1615.0], [60, 1615.0], [61, 1615.0], [62, 1615.0], [63, 1615.0], [64, 1615.0], [65, 1615.0], [66, 1615.0], [67, 1615.0], [68, 1615.0], [69, 1615.0], [70, 1615.0], [71, 1615.0], [72, 1615.0], 

In [315]:
count = getIterationCount(T, D, 0.85)
print("No. of iterations required after considering Trust Rank: " + str(count))

No. of iterations required after considering Trust Rank: 376


In [316]:
TrustRankScore = []
for i in range(1, len(D)):
    if D[i] != 0:
        TrustRankScore.append([i, D[i]])

TrustRankScore = sorted(TrustRankScore, key = operator.itemgetter(1), reverse = True)

In [317]:
print(TrustRankScore)

[[1, 1615.0], [2, 1615.0], [3, 1615.0], [4, 1615.0], [5, 1615.0], [6, 1615.0], [7, 1615.0], [8, 1615.0], [9, 1615.0], [10, 1615.0], [11, 1615.0], [12, 1615.0], [13, 1615.0], [14, 1615.0], [15, 1615.0], [16, 1615.0], [17, 1615.0], [18, 1615.0], [19, 1615.0], [20, 1615.0], [21, 1615.0], [22, 1615.0], [23, 1615.0], [24, 1615.0], [25, 1615.0], [26, 1615.0], [27, 1615.0], [28, 1615.0], [29, 1615.0], [30, 1615.0], [31, 1615.0], [32, 1615.0], [33, 1615.0], [34, 1615.0], [35, 1615.0], [36, 1615.0], [37, 1615.0], [38, 1615.0], [39, 1615.0], [40, 1615.0], [41, 1615.0], [42, 1615.0], [43, 1615.0], [44, 1615.0], [45, 1615.0], [46, 1615.0], [47, 1615.0], [48, 1615.0], [49, 1615.0], [50, 1615.0], [51, 1615.0], [52, 1615.0], [53, 1615.0], [54, 1615.0], [55, 1615.0], [56, 1615.0], [57, 1615.0], [58, 1615.0], [59, 1615.0], [60, 1615.0], [61, 1615.0], [62, 1615.0], [63, 1615.0], [64, 1615.0], [65, 1615.0], [66, 1615.0], [67, 1615.0], [68, 1615.0], [69, 1615.0], [70, 1615.0], [71, 1615.0], [72, 1615.0], 

In [320]:
print("Transition Matrix is:")
print(T)

Transition Matrix is:
[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
